FROM alpine
LABEL maintainer="Erik Edin <erikedin.name@gmail.com>"

ENV PYTHONUNBUFFERED=0

COPY requirements.txt /app/requirements.txt

RUN apk update && apk add python3
RUN pip3 install -r /app/requirements.txt

COPY . /app/

CMD ["python3", "/app/niancatbot/niancatbot.py"]