name:                niancat
version:             0.1.0.0
github:              "dandeliondeathray/niancat-micro"
license:             Apache-2.0
author:              "Tomas Aschan"
maintainer:          "1550920+tomasaschan@users.noreply.github.com"
copyright:           "2019 Tomas Aschan"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/niancat#readme>

dependencies:
- base
- servant-server
- warp

library:
  source-dirs: src/lib
  ghc-options:
    - -Wall
  dependencies:
    - aeson
    - data-default-class
    - http-types
    - mtl
    - scotty
    - stm
    - text
    - text-show
    - vector
    - wai
    - wai-extra

executables:
  niancat-exe:
    main:                Main.hs
    source-dirs:         src/app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - niancat

tests:
  niancat-test:
    main:                Spec.hs
    source-dirs:         test/lib
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - niancat

    - aeson
    - bytestring
    - data-default-class
    - http-types
    - mtl
    - stm
    - text
    - text-show
    - scotty

    - wai
    - wai-extra
    - hspec
    - hspec-discover
    - hspec-wai
    - hspec-wai-json
    - QuickCheck
    - quickcheck-instances

default-extensions:
- DataKinds
- TypeOperators
# - FlexibleInstances
# - GeneralizedNewtypeDeriving
# - MultiParamTypeClasses
- OverloadedStrings
- ScopedTypeVariables
# - ConstraintKinds
# - FlexibleContexts
# - NoImplicitPrelude
# - DataKinds
# - DeriveGeneric
# - DuplicateRecordFields
# - TypeApplications
# - ScopedTypeVariables
