FROM alpine
LABEL maintainer="Erik Edin <erikedin.name@gmail.com>"

RUN apk update && apk add openjdk8-jre

RUN adduser -D user
USER user
WORKDIR /app

COPY target/scala-2.12/niancat-assembly-1.0rc1.jar /app/niancat.jar

CMD ["java", "-jar", "/app/niancat.jar"]